### ISSUE TITLE
Please add notice that an external ice/turn server is used by default or make it configurable

### ISSUE THREAD

**Issue by okaufmann** [PHPJunior/laravel-video-chat#1]
Hi,

Thanks for your work! I like realtime apps and so I tried this package.

I found the following line, where a external not mentioned external server is used for video calling (or am I wrong?).

https://github.com/PHPJunior/laravel-video-chat/blob/master/resources/assets/js/components/ChatRoom.vue#L283

I think that should be mentioned somewhere or made configurable.

best regards

**Comment by PHPJunior** [comment]
Thanks bro...  i will change it 😁😁😁
