### ISSUE TITLE
Invalid SDP on start video call

### ISSUE THREAD

**Issue by Dwiraj** [PHPJunior/laravel-video-chat#17]
Hello,

I am implementing Text and Video chat using your package in laravel 5.6.

All things are working fine in text chat, nothing issue in it. But my problem is in video chat.

When i start video call and opponent  clicked on Answer button  here is an error showing in developer console.

![image](https://user-images.githubusercontent.com/16116465/46123696-85e57080-c23d-11e8-9c35-12be1f677c5c.png)

Can you guide me in this. I don't have any idea about SDP.

Thank you !!!

**Comment by khristoff** [comment]
Same problem, any ideas?

**Comment by Dwiraj** [comment]
Hello @khristoff 

You only need to concat  "\n" character to your SDP.
